### ISSUE TITLE
coloredState: true, only works for columns

### ISSUE THREAD

**Issue by Doughboy99** [doctorfree/MMM-MacAddressScan#1]
colorStateOffline and colorStateOnline only work when using columns.

**Comment by doctorfree** [comment]
I was able to replicate this issue. I'll look into it.

**Comment by doctorfree** [comment]
I pushed an initial fix for this issue after testing with several configurations, column and row device display using different coloring options. @Doughboy99 let me know if this resolves the issue for you or if there are additional changes needed.

Note that when coloring devices by state I opted to use white and gray for online/offline and color the icon according to the color state properties. This is so the state is more readily apparent. This choice on my part can be revisited if it is an issue (e.g. device display sans icon). This release should at least be an improvement and we can discuss further mods.

To update:

```
cd /path/to/MagicMirror/modules/MMM-MacAddressScan
git pull
npm install
```

**Comment by Doughboy99** [comment]
HI

Actually that is perfect. Applying the colour to the icon highlights whether an item is on or offline without being garish.

Just a further note the instructions for applying css changes don't seem to work. I need to change the font size used to display the network devices as well as display module nicely in "top-right" position. The instructions suggest using 

.MMM-MacAddressScan .headerDevCell {
  font-size: 28px;
}

But this has no effect in custom.css or the modules own .css file.

Thanks

**Comment by doctorfree** [comment]
Thanks for opening this issue @Doughboy99 - quality feedback definitely helps improve a project. I will look into the font size issue you raise. Cheers!

**Comment by Doughboy99** [comment]
That would be great. The module seems to be ignoring anything in MacAddressScan.css. At least for me. Please screenshot
![screen](https://user-images.githubusercontent.com/57818992/159389936-b5d3e828-b6be-4064-a6f5-5d39c6020acb.png)
!

**Comment by doctorfree** [comment]
@Doughboy99 I've opened a new issue to deal with the css problem you report. Upon initial examination I find I can control the font size in this module with the following:

~~~
.MMM-MacAddressScan .module-header {
   font-size: 24px;
}
.MMM-MacAddressScan .deviceCell {
    font-size: 28px;
}
.MMM-MacAddressScan .headerDevCell {
    font-size: 32px;
}
~~~

I am still investigating and testing. Let me know, in the open issue on this, what you experience using something like the above.
