### ISSUE TITLE
Font size css setting has no effect

### ISSUE THREAD

**Issue by doctorfree** [doctorfree/MMM-MacAddressScan#2]
@Doughboy99 reported:

The instructions for applying css changes don't seem to work. I need to change the font size used to display the network devices as well as display module nicely in "top-right" position. The instructions suggest using

.MMM-MacAddressScan .headerDevCell {
font-size: 28px;
}

But this has no effect in custom.css or the modules own .css file.

**Comment by doctorfree** [comment]
Trying the following:

~~~
.MMM-MacAddressScan .module-header {
   font-size: 24px;
}
.MMM-MacAddressScan .deviceCell {
    font-size: 28px;
}
.MMM-MacAddressScan .headerDevCell {
    font-size: 32px;
}
~~~

**Comment by Doughboy99** [comment]
Hi

The first two work when placed in MMM-MacAddressScan.css but appear to have no effect when put in the MagicMirror custom.css file.

".MMM-MacAddressScan .headerDevCell {
    font-size: 32px;
}"
Has no effect regardless, presumably because it is for use with rows.

Can you tell me how to increase the spacing between the device icon and the device name and ip address text see attached screen shot

![mmm](https://user-images.githubusercontent.com/57818992/159581881-f446a37d-19bd-4a17-80c5-42657c457b41.png)

Thanks

**Comment by doctorfree** [comment]
@Doughboy99 check the "customCss:" setting in your `MagicMirror/config/config.js`. Perhaps it is set to something other than `custom.css`. I use several different custom css files in the MirrorCommand project. If in fact you are using `custom.css` and the same styling that works in MMM-MacAddressScan.css does not work there then I have some work to do. Hopefully it is just locating the right custom css file and placing your entries there.

I don't know that the spacing between icon and device name can be styled. I will look into it.

**Comment by doctorfree** [comment]
@Doughboy99 I've pushed changes to the default `MMM-MacAddressScan.css`. I was able to specify the spacing between icon and device name by adjusting the `padding-right` setting as follows:

~~~
.MMM-MacAddressScan .deviceCell i {
  padding-left: 0;
  padding-right: 10px;
}
~~~

Increase that to 20px or whatever you want. The problem was the default css was still referencing older class names. A `git pull` should get you up-to-date css. I am still testing these changes so there may be additional code changes coming soon. Thanks for helping me with this.

**Comment by Doughboy99** [comment]
My config.js didn't have `customCss: "css/custom.css",` as an  entry. Adding makes css entries for your module get noticed.
Interestingly the config.js created when MagicMirror is installed doesn't have the custom.css entry but css changes that affect magicmirror "globally" still work.

For instance I have 
`body {
  margin: 5px;
  height: calc(100% - 0px);
  width: calc(100% - 10px);
} 

.region.bottom.bar .container .module.newsfeed {
  height: 60px; 		///* height of the module with maximum lines possible */
}`

which works regardless of whether  the custom.css option has been entered in config.js.

Anyway it's working now.

Thanks again.

**Comment by doctorfree** [comment]
Interesting. The custom.css must get loaded twice, if configured in config.js, once when MagicMirror starts up and again when the modules are loaded. I am guessing. It's outside my current understanding. Anyway, good to hear it's working for you now. I appreciate your raising these issues and helping me resolve them.
